FROM artifactory.build.nvda.ai/maglev-containers/mldevprod/tools/dispatch-stage:v20230919

COPY src/dispatch/plugins/dispatch_slack/middleware.py /usr/local/lib/python3.11/site-packages/dispatch/plugins/dispatch_slack/middleware.py
